sudo: required
language: node_js
node_js:
  - "11"
cache:
  directories:
  - node_modules
install:
  - npm install -g embark
  - npm install
script:
  - npm run test
after_script:
  - npm run coverage